apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
  namespace: file-sharing
data:
  FILE_SERVICE_PORT: "8082"
  FILE_GRPC_PORT: "50052"
  FILE_SERVICE_HOST: "0.0.0.0"
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DATABASE: "file_sharing"
  STORAGE_TYPE: "minio"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "file-sharing"
  MINIO_USE_SSL: "false"
  KAFKA_BROKERS: "kafka:9092"
  AUTH_SERVICE_GRPC: "auth-service:50051"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"

