apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: file-sharing
data:
  NOTIFICATION_SERVICE_PORT: "8083"
  NOTIFICATION_GRPC_PORT: "50053"
  NOTIFICATION_SERVICE_HOST: "0.0.0.0"
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DATABASE: "file_sharing"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_GROUP_ID: "notification-service"
  KAFKA_TOPIC: "file-events"
  AUTH_SERVICE_GRPC: "auth-service:50051"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"

